doctrine:
  orm:
    mappings:
      BudgetmanagerBundle:
          is_bundle: true
          type: annotation
          dir: 'src/Entity'
          prefix: 'ICS\BudgetmanagerBundle\Entity'
          alias: Budgetmanager