services:
    _defaults:
        autowire: true
        autoconfigure: true
    # Chargement des services
    ICS\BudgetmanagerBundle\Controller\:
        resource: "../src/Controller"
        tags: ['controller.services_arguments']
    ICS\BudgetmanagerBundle\Service\:
        resource: "../src/Service"
        tags: ['controller.services_arguments']
    ICS\BudgetmanagerBundle\Command\:
        resource: "../src/Command"
        tags: ['controller.services_arguments']
    ICS\BudgetmanagerBundle\Twig\:
        resource: "../src/Twig"
        tags: ['controller.services_arguments']
    ICS\BudgetmanagerBundle\Form\:
        resource: "../src/Form"
        tags: ['controller.services_arguments']
